packages:
  - 'packages/**/*'
  - 'apps/**/*'

pnpm:
  overrides:
    '@shuttle-ai/type': '^0.0.5'
    '@shuttle-ai/agent': '^0.0.5'
    '@shuttle-ai/client': '^0.0.5'
    '@shuttle-ai/render-react': '^0.0.5'
    'zod': '^4.3.5'
    'knex': '^3.1.0'
    'classnames': '^2.5.1'
    'react': '^18.2.0'
    'react-dom': '^18.2.0'
    'antd': '^6.1.1'
    'axios': '^1.13.2'
    '@ant-design/icons': '^6.1.0'
    'langchain': '^1.2.17'
    '@langchain/core': '^1.1.19'
    '@langchain/openai': '^1.2.4'
